### ISSUE TITLE
05 example failed on ubuntu20.04 server with invalid argument error

### ISSUE THREAD

**Issue by gwnet** [shuveb/io_uring-by-example#8]
please see my debug screen.

it goes into below error path, cqe.res value is strange. looks like no one assign it.

please guide me.

intel@wcp116:~/wayne/miniobin/distributedminioBWprofile$ uname -a
Linux wcp116 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
intel@wcp116:~/wayne/miniobin/distributedminioBWprofile$ 

intel@wcp116:~/wayne/io_uring-by-example$ sudo ./webserver_liburing 
hello from Wayne debug here!
2
Async request failed: Invalid argument for event: 0

![image](https://user-images.githubusercontent.com/7543276/89910271-95e47e80-dc22-11ea-8bfb-16923409bd7f.png)

**Comment by shuveb** [comment]
Hello,

Looks like you're running this on Windows Services for Linux (WSL). I'm not sure it supports io_uring. Can you confirm if you are running this on WSL Ubuntu or you're running this inside of a Linux virtual machine?

**Comment by gwnet** [comment]
no, I run on Xeon HW, you see Visual Studio because I use Visual Studio remote debug feature to debug the application running in the linux. it is not WSL. for sure. :)

I run this on Ubuntu server 20.04.

**Comment by gwnet** [comment]
any thing I can do?

**Comment by shuveb** [comment]
Hello,

I see from your uname output that your kernel is v5.4. However, according to [liburing documentation for the accept operation](https://unixism.net/loti/ref-liburing/submission.html#c.io_uring_prep_accept), support for accept was added in kernel v5.5. That's the problem. You can run the probe.c example program from [Lord of the io_uring example programs repo](https://github.com/shuveb/loti-examples) to determine which io_uring operations your kernel supports.

Tip: You can use Arch Linux which usually runs the most recent kernels, or you can install [more recent kernels on Ubuntu](https://wiki.ubuntu.com/Kernel/MainlineBuilds) as well. Make sure you run the probe program to see if all required features to run an example are supported by your running kernel.

Hope that helps!

**Comment by gwnet** [comment]
@shuveb Yes, you are right. I will install latest kernel with one VM to test again.

intel@wcp116:~/wayne/loti-examples/build$ sudo ./probe
[sudo] password for intel: 
You are running kernel version: 5.4.0-42-generic
This program won't work on kernel versions earlier than 5.6
Report of your kernel's list of supported io_uring operations:
Segmentation fault
intel@wcp116:~/wayne/loti-examples/build$

**Comment by gwnet** [comment]
it works after I update kernel to 5.8. :)
